const APP_PATH = {
    HOME: '/',
    SIGN_UP: '/sign-up',
    SIGN_IN: '/sign-in',
    SEND_OTP: '/send-otp',
    VERIFY_OTP: '/verify-otp',
    MY_COMMUNITY: '/my-community',
    CHAT: '/chat',
    TEMP_PAGE: '/temp-page',
    PROFILE: '/profile',
    FIND_FRIENDS: '/find-friends',
    EDIT_PROFILE: '/setting/edit-profile',
    CHANGE_PASS: '/setting/change-pass',
    FRIEND_REQ: '/setting/friend-request',
    ALBUM: '/profile/album',
    FRIEND: '/profile/friend',
    NOTIFICATION: '/notification',
    DETAIL_POST: '/detail-post',
};
export default APP_PATH;
